### ISSUE TITLE
GUI Issue 

### ISSUE THREAD

**Issue by ANDREWNGT** [sammmlow/QLUSTER#1]
GUI is cutoff halfway as was observed in LEOGPS. Adding this issue to serve as a reminder. 

Windows 10, 150% size of text, apps and other items. 
1920 x 1080 resolution.

**Comment by sammmlow** [comment]
Resolved; programmed the GUI class to sample the user's monitor pixel-per-inch, and then compute a customised scaling of the DPI thereafter. Closing.
